### ISSUE TITLE
Interaction between time-dependent covariate and fixed covariate in when modeling a survival outcome

### ISSUE THREAD

**Issue by ElsaVazquez29** [DenisRustand/INLAjoint#30]
Hi Denis,

I am trying to fit a joint model for longitudinal and time-to-event data. In this model, I want to check if there is an interaction term between a longitudinal outcome (time-dependent covariate) and a treatment variable (fixed covariate) when modeling a survival outcome.

I was not able to find an example of that in your vignette and wanted to ask if that is possible in this package?

Thanks in advance for your help!

**Elsa  Vazquez Arreola**

**Comment by DenisRustand** [comment]
Hi Elsa, 
This feature is not yet available but it is possible to do. Since it may take time before it's there, you can reach me at INLAjoint@gmail.com if you want us to try to write a code specific to your needs as it's faster to do specific models rather than general developments.
Best,
Denis Rustand
